name: tuist build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  build:
    name: Build default scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
      - name: Setup
        run: |
          tuist up
      - name: Build Frameworks
        run: |
          tuist build Kite
      - name: Build App
        run: |
          tuist build App
      - name: Test
        run: |
          xcodebuild -project Ground.xcodeproj -scheme "OpenWeatherTests" -configuration "Debug" -destination "name=iPhone 8,OS=14.0" -sdk "iphonesimulator14.0" OTHER_SWIFT_FLAGS='$(inherited) -suppress-warnings' build-for-testing test-without-building
